title: Functional Genomics Platform
description: IBM Functional Genomics Platform, data and analytics for multi-omics research at scale.
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
